### PR TITLE
Qingyi‘s Pull Request

### PR DESCRIPTION
**Pull request by liuqin26**
Created constraints for username and password using regex checker;
Added the method changePassword in UserManager

### CODE REVIEW

**Review by howardxhc — COMMENTED** [review]
- New functionality added (check password conditions are good)
- Should this class belong to use case or controller? Because of course it doesn't depend on anything, but if it is in the use case class, we need another set of controller methods so that UI level can use them.
- New methods of setting new password satisfies CA, looks right
- NEED UI Collaboration on password check, might need more methods on the controller level

**Comment by zhen-s** [comment]
Just need to write simple testcases that does not depend on any of the interior layers, which should be easy. This class ensures the passwords are usable, and allows users to change which the passwords, which is very reasonable. I think this class can remain in the controller layer as not much of the inner interactions with the entities matter to this class as only a check

**Comment by Parkrytom** [comment]
The file itself can work well! But maybe it should be in the Controller file.

**Comment by liuqin26** [comment]
> Created constraints for username and password using regex checker; Added the method changePassword in UserManager

I've added some new changes, please review the following:
- Modified ItemStorage.java by changing the addItem and deleteItems methods (defined "identical item" differently).
- Moved RegexChecker.java to Controller.
- Added a new toString method in Item.java for comparing identical items.
- Wrote printItemName, addElement, removeElement in InfoFacade.java.

**Pull request merged**
