### PR TITLE
Fix the buying problem

### PR DESCRIPTION
**Pull request by EVAXZC**
Fix the buying problem

### CODE REVIEW

**Comment by InxiQ** [comment]
Looks good I think we can merge it!

**Comment by Parkrytom** [comment]
Now items can be extracted from item storage which is good!

**Comment by zhen-s** [comment]
I think we also need how many of the same item is sold during a transaction, so not the entire item object is deleted from the itemStorage, instead only a certain quantity is deducted from the item and removed from storage iff quantity=0

**Comment by howardxhc** [comment]
> I think we also need how many of the same item is sold during a transaction, so not the entire item object is deleted from the itemStorage, instead only a certain quantity is deducted from the item and removed from storage iff quantity=0

I think that's something the deleteElement method in itemStorage should go for, not on the controller level.

**Comment by EVAXZC** [comment]
> I think we also need how many of the same item is sold during a transaction, so not the entire item object is deleted from the itemStorage, instead only a certain quantity is deducted from the item and removed from storage iff quantity=0

Since when we store the item did not change the quantity so we just simply delete the item from the item storage.

**Pull request merged**
